name: 03-Worfows-Runners

on:
    workflow_dispatch:

jobs:

    ubuntu-runner:

        runs-on: ubuntu-latest
        steps:
            - name: SHOW OS
              run: |
                echo "This job is running on Ubuntu"
                echo "Runner OS: $RUNNER_OS"

    windows-runner:

        runs-on: windows-latest
        steps:
            - name: SHOW OS
              shell: bash 
              run: | 
                echo "This job is running on Windows"
                echo "Runner OS: $RUNNER_OS" 

    mac-runner:

        runs-on: macos-latest
        steps:

            - name: SHOW OS
              run: |
                echo "This job is running on Macos"
                echo "Runner OS: $RUNNER_OS" 


