name: 06 - Context
run-name: 06 - Context | DEBUGG - ${{inputs.debug}} 
 

on: 
    #push:
    workflow_dispatch:
        inputs:
             debug:
                type: boolean
                default: false 
                
env:
    MY_WORKFLOW_VAR: "workflow-ariel"
    MY_OVERWRITTEN_VAR:  "workflow-ariel" 

jobs:

    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: "job"
            MY_OVERWRITTEN_VAR: "job"
        steps:
            - name: Display Information
              run: |
                echo "Event name: ${{github.event_name}}"
                echo "Ref: ${{github.ref}}"
                echo "SHA: ${{github.sha}}"
                echo "Repo: ${{ github.repository }}"
                echo "Branch: ${{ github.ref_name }}"
                echo "Autor: ${{ github.actor }}"
                echo "Workflow: ${{github.workflow}}"
                echo "Run Id: ${{github.run_id }}"
                echo "Run Number: ${{github.run_number}}"

            - name: Runners
              run: |
                echo "OS: ${{ runner.os }}"
                echo "Directorio temp: ${{ runner.temp }}"

            - name: Retrieve Variable 
              run: |
                echo "Variable value: ${{vars.MY_VAR }}"

            - name: Print Env Variables

              env:
                MY_OVERWRITTEN_VAR: "step"

              run: |
                 echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}" 
                 echo "Overwitten env: ${{env.MY_OVERWRITTEN_VAR}}"
                 echo ""

            - name: Print Env Variables-2

              run: |
                 echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}" 
                 echo "Overwitten env: ${{env.MY_OVERWRITTEN_VAR}}"
    
    echo-data2:
        runs-on: ubuntu-latest

        steps:
            - name: Print Env Variables
              run: |
                 echo "Workflow env: $MY_WORKFLOW_VAR" 
                 echo "Overwitten env: $MY_OVERWRITTEN_VAR"


            