name: 09 - exercise

on:
    #push:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: exit 1
      - name: Second Step
        id: second_step_id
        if: ${{ failure() }}
        run: echo "This step runs if the first step failed."
      - name: Third Step
        if: ${{ success() }}
        run: echo "This step runs if the first step succeeded."

      - name: what is the status for the second step
        run: |
            echo " the status od the decond step is: ${{ steps.second_step_id.outcome}}"
    
        