name: 13 - Using Caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: Wheter to execute cache step
                type: boolean
                default: true


jobs:

    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app

        steps:
            # 1.    Checkout the code 
            - name: Checkout code
              uses: actions/checkout@v4

            # 2.    Install dependencies

            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: '20.x'

            - name: Install Dependencies
              run: npm install
             
            # 3.   Linting, formatting, unit testing, building   
            - name: Testing 
              run: npm run test
            
            - name: Building
              run: npm run build
            
            # 4.    Deploy to nonprod
            - name: Deploying to NONPROD
              run: echo "Deploying to NONPROD ..."

            

