name: 15 - Working With Matrices

on:
  workflow_dispatch:

jobs:

  backwards-compatibility:
    name: ${{ matrix.os}}-${{ matrix.node-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True # if it is true if any job fails all the jobs is going to skip
      matrix: 
        node-version: [18.x, 20.x, 21.x]
        os:
          - ubuntu-latest
          - windows-latest
        include: 
          # add a the combination: ubuntu-latest-16.x (just this conbination - just add this new job)
          - os: ubuntu-latest
            node-version: 16.x

          # add a new job: ubuntu-latest.21.x/experimental
          - os: ubuntu-latest
            node-version: 21.x
            tag: experimental

    steps:

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 1


      - name: Perfom some test
        run: |
          echo "Running test on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version}}"
          sleep 10

      - name: Upload test results
        run: echo "Uploading test result"

  include-example:

    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [red, green]
        shape: [circle, square]
        size: [small, large]
        include:

          - opacity: 50
          # todo lo que tenga red se le añade un triangle si no tiene shape
          - color: red
            shape: triangle

            # todo lo que tenga red y no tenga opacity se le agregara un 75
          - color: red
            opacity: 75
          
            # todo lo que tenga circle se le agregara un opacity (es overwrite)
          - shape: circle
            opacity: 100


        # the exclude command is executed before than the includ3e command: exclude --> include 
        exclude: 
          - opacity: 75


    steps:
      - name: Dummy step
        run: echo " ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }} "




