name: 16 - Working With Environments

on:
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: stagging

jobs:

    echo:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-env }}
        env:
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: Echo Var
              run: |
                echo "Env variable: ${{ env.my-env-value }}"

