# See 17-custom-actions/README.md for more information
# about how to create and use custom actions in workflows.

name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:

      url:
        type: choice 
        options: 
          - 'https://www.google.com'
          - 'https://www.google-inbvalid-url.com'
          - 'invalid-googlewerdfw.com'
   
      max_trial:
        description: Maximun number of trials until action fails
        default: '10'
        required: false

      delay:
        description: Delay in seconds detween trials
        default: '5'
        required: false
      

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
            url: ${{ inputs.url}}
            max_trials: ${{ inputs.max_trial }}
            delay: ${{ inputs.delay }}
        